name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'app/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd app
        npm ci
        
    - name: Type check
      run: |
        cd app
        npm run type-check
        
    - name: Lint
      run: |
        cd app
        npm run lint
        
    - name: Format check
      run: |
        cd app
        npm run format:check
        
    - name: Run tests
      run: |
        cd app
        npm run test:run
        
    - name: Build
      run: |
        cd app
        npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: app/dist/
        retention-days: 7 
